org.talend.components.cosmosDB.service.I18nMessage.databaseNotExist=La base de donn\u00E9es [{0}] n''existe pas.
org.talend.components.cosmosDB.service.I18nMessage.noResultFetched=Aucun r\u00E9sultat r\u00E9cup\u00E9r\u00E9 depuis la collection source.
org.talend.components.cosmosDB.service.I18nMessage.connectionKODetailed=\u00C9chec de la connexion : {0}
org.talend.components.cosmosDB.service.I18nMessage.destinationUnreachable=L''h\u00F4te distant est inaccessible.
org.talend.components.cosmosDB.service.I18nMessage.vacantDBID=L''ID de la base de donn\u00E9es est vide.
org.talend.components.cosmosDB.service.I18nMessage.connectionSuccess=Connexion OK
org.talend.components.cosmosDB.service.I18nMessage.notValidAddress = Impossible d''acc\u00E9der \u00E0 l''adresse ''{0}'' d\u00E9finie dans le connecteur car l''acc\u00E8s est interdit par la configuration (local ([local]), multicast ([multicast]), ou unsecured ([non_secured])). Utilisez une adresse diff\u00E9rente et r\u00E9essayez.
